//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Controller.java
//  @ Date : 2017. 05. 05.
//  @ Author : 
//
//




public class Controller {
	/*public void mouseClicked(MouseEvent e) {
	}*/
}
